import { mkdtemp, readFile, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import type { ProjectBrief } from '../src/brief.js';
import { run, type CliDeps, type Prompts } from '../src/cli.js';
import { GenerationError } from '../src/errors.js';
import { FixtureProvider, type ReadmeProvider } from '../src/generator.js';
import { STYLE_IDS } from '../src/styles.js';
import { captureIO, createMockFetch, fakeSecrets, json, loadFixture, type MockFetchOptions } from './helpers.js';

const URL_ = 'https://github.com/acme/widget';
const tmp = () => mkdtemp(path.join(os.tmpdir(), 'repo2readme-cli-'));

async function cli(argv: string[], opts: { fixture?: string | null; mock?: MockFetchOptions; deps?: Partial<CliDeps>; env?: Record<string, string> } = {}) {
  const io = captureIO();
  const fx = opts.fixture === null ? null : loadFixture(opts.fixture ?? 'widget');
  const mock = createMockFetch(fx, opts.mock);
  const cwd = opts.deps?.cwd ?? (await tmp());
  const code = await run(argv, { fetch: mock.fetch, env: opts.env ?? {}, cwd, stdout: io.stdout, stderr: io.stderr, isTTY: false, ...opts.deps });
  return { code, out: io.out, err: io.err, requests: mock.requests, cwd };
}

describe('CLI: happy paths', () => {
  it.each(STYLE_IDS)('--dry-run produces clean Markdown for style %s', async (style) => {
    const r = await cli([URL_, '--style', style, '--dry-run', '--provider', 'fixture']);
    expect(r.code).toBe(0);
    expect(r.out).toMatch(/^<!-- Generated by repo2readme from https:\/\/github\.com\/acme\/widget/);
    expect(r.out).toContain('\n# widget\n');
    expect(r.out.length).toBeGreaterThan(200);
    expect(r.out).not.toMatch(/\{\{|\}\}|TODO|lorem ipsum|undefined|null|\[object Object\]/i);
    expect(r.err).toContain('Analyzing repository acme/widget');
    expect(r.err).toContain('Dry run: README printed to stdout');
    expect(r.err).toMatch(/Sources inspected \(\d+\): README\.md/);
    expect(r.err).toContain('Review the README before using it');
  });

  it('writes README.generated.md atomically and prints a summary', async () => {
    const r = await cli([URL_, '-s', 'professional', '--provider', 'fixture']);
    expect(r.code).toBe(0);
    const written = await readFile(path.join(r.cwd, 'README.generated.md'), 'utf8');
    expect(written).toContain('# widget');
    expect(written).toContain('npm install --global @acme/widget');
    expect(r.out).toContain('Created README.generated.md');
    expect(r.out).toContain('all read-only GET');
  });

  it('flags generated badges in the trendy style', async () => {
    const r = await cli([URL_, '-s', 'trendy', '--dry-run', '--provider', 'fixture']);
    expect(r.out).toContain('## Verify before publishing');
    expect(r.out).toMatch(/\*\*Badge\*\* `https:\/\/img\.shields\.io\/badge\/license-MIT-blue`/);
    expect(r.err).toContain('Verify before publishing:');
  });

  it('handles a sparse, unlicensed, archived repository', async () => {
    const r = await cli(['https://github.com/someone/pyapp', '-s', 'comprehensive', '--dry-run', '--provider', 'fixture'], { fixture: 'pyapp' });
    expect(r.code).toBe(0);
    expect(r.out).toContain('# pyapp');
    expect(r.out).toContain('archived');
    expect(r.out).not.toMatch(/^## License/m);
    expect(r.out).toContain('No license was detected');
    expect(r.requests.some((q) => q.url.includes('/trunk/pyproject.toml'))).toBe(true);
  });

  it('runs the interactive flow with prompts', async () => {
    const asked: string[] = [];
    const prompts: Prompts = {
      input: async (o) => {
        asked.push(o.message);
        if (o.message.startsWith('GitHub')) {
          expect(o.validate?.('https://gitlab.com/x/y')).toMatch(/Only github\.com/);
          return URL_;
        }
        return o.default ?? '';
      },
      select: async (o) => {
        asked.push(o.message);
        expect(o.choices.map((c) => c.name)).toEqual(['Professional', 'Trendy', 'Minimalist', 'Comprehensive']);
        return 'minimalist';
      },
      confirm: async () => false,
    };
    const r = await cli(['--provider', 'fixture'], { deps: { isTTY: true, prompts } });
    expect(r.code).toBe(0);
    expect(asked).toEqual(['GitHub repository URL:', 'Style:', 'Output path:']);
    expect(await readFile(path.join(r.cwd, 'README.generated.md'), 'utf8')).toContain('## Install');
  });

  it('uses the OpenAI-compatible provider with a mocked endpoint', async () => {
    let sentBody = '';
    const content = {
      title: 'widget',
      sections: [
        { heading: 'Overview', body: 'Render configurable widgets from the command line.' },
        { heading: 'Install', body: '```sh\nnpm install --global @acme/widget\n```' },
        { heading: 'Status', body: '![coverage](https://img.shields.io/codecov/c/github/acme/widget)' },
      ],
      warnings: ['Coverage badge is a guess.'],
    };
    const key = fakeSecrets.xaiKey();
    const r = await cli([URL_, '-s', 'professional', '--dry-run'], {
      env: { REPO2README_API_KEY: key },
      mock: {
        routes: [
          {
            match: 'api.x.ai',
            respond: (_u, init) => {
              sentBody = String(init?.body);
              return json({ choices: [{ message: { content: JSON.stringify(content) }, finish_reason: 'stop' }] });
            },
          },
        ],
      },
    });
    expect(r.code).toBe(0);
    expect(r.out).toContain('npm install --global @acme/widget');
    expect(r.out).toMatch(/\*\*Badge\*\* `https:\/\/img\.shields\.io\/codecov/);
    expect(r.out).toContain('**Note:** Coverage badge is a guess.');
    expect(r.err).toContain('grok-4.6 via api.x.ai (key from REPO2README_API_KEY)');
    expect(`${r.out}${r.err}`).not.toContain(key);
    expect(sentBody).not.toContain('fixture-env-file-sentinel-value');
    expect(sentBody).toContain('package.json');
  });
});

describe('CLI: safety guarantees', () => {
  it('only issues GET requests to GitHub and never requests excluded files', async () => {
    const r = await cli([URL_, '-s', 'comprehensive', '--dry-run', '--provider', 'fixture', '--verbose']);
    expect(r.code).toBe(0);
    const gh = r.requests.filter((q) => /github(usercontent)?\.com/.test(new URL(q.url).hostname));
    expect(gh.length).toBeGreaterThan(0);
    expect(gh.every((q) => q.method === 'GET' && q.body === undefined)).toBe(true);
    const urls = r.requests.map((q) => q.url);
    for (const bad of ['/.env', 'node_modules', 'vendor/', '.pem', '.png', 'huge-reference.md', 'dist/']) {
      expect(urls.filter((u) => u.endsWith(bad) || (bad !== '/.env' && u.includes(bad)))).toEqual([]);
    }
    expect(urls.some((u) => u.endsWith('/.env.example'))).toBe(true);
    expect(r.err).toMatch(/GET https:\/\/api\.github\.com\/repos\/acme\/widget -> 200/);
  });

  it('never passes excluded or secret content to the provider', async () => {
    let seen: ProjectBrief | undefined;
    const spy: ReadmeProvider = {
      name: 'spy',
      generateReadme: async (brief, style) => {
        seen = brief;
        return new FixtureProvider().generateReadme(brief, style);
      },
    };
    const aws = fakeSecrets.awsKey();
    const io = captureIO();
    const fx = loadFixture('widget', { 'docs/configuration.md': `key: ${aws}` });
    const mock = createMockFetch(fx);
    const code = await run([URL_, '-s', 'professional', '--dry-run'], { fetch: mock.fetch, env: {}, cwd: await tmp(), stdout: io.stdout, stderr: io.stderr, isTTY: false, providerFactory: () => spy });
    expect(code).toBe(0);
    const s = JSON.stringify(seen);
    expect(s).not.toContain('fixture-env-file-sentinel-value');
    expect(s).not.toContain(aws);
    expect(seen?.files.map((f) => f.path)).not.toContain('.env');
    expect(io.err).toMatch(/Redacted 1 potential secret\(s\) in docs\/configuration\.md/);
  });

  it('never prints the GitHub token', async () => {
    const token = fakeSecrets.githubToken();
    const r = await cli([URL_, '-s', 'professional', '--dry-run', '--provider', 'fixture', '--verbose'], { env: { GITHUB_TOKEN: token } });
    expect(r.code).toBe(0);
    expect(r.requests[0]?.headers.authorization).toBe(`Bearer ${token}`);
    expect(`${r.out}${r.err}`).not.toContain(token);
  });

  it('refuses to overwrite README.generated.md before making any request', async () => {
    const dir = await tmp();
    await writeFile(path.join(dir, 'README.generated.md'), 'keep me');
    const r = await cli([URL_, '-s', 'professional', '--provider', 'fixture'], { deps: { cwd: dir } });
    expect(r.code).toBe(6);
    expect(r.err).toMatch(/already exists; refusing to overwrite/);
    expect(r.err).toMatch(/--force/);
    expect(r.requests).toEqual([]);
    expect(await readFile(path.join(dir, 'README.generated.md'), 'utf8')).toBe('keep me');

    const forced = await cli([URL_, '-s', 'professional', '--provider', 'fixture', '--force'], { deps: { cwd: dir } });
    expect(forced.code).toBe(0);
    expect(await readFile(path.join(dir, 'README.generated.md'), 'utf8')).toContain('# widget');
  });

  it('overwrites an explicitly named --output', async () => {
    const dir = await tmp();
    await writeFile(path.join(dir, 'README.md'), 'old');
    const r = await cli([URL_, '-s', 'minimalist', '--provider', 'fixture', '--output', 'README.md'], { deps: { cwd: dir } });
    expect(r.code).toBe(0);
    expect(await readFile(path.join(dir, 'README.md'), 'utf8')).toContain('# widget');
  });
});

describe('CLI: errors', () => {
  it.each([
    ['https://gitlab.com/acme/widget', /Only github\.com/],
    ['https://github.com/acme', /does not name a repository/],
    ['https://github.com/acme/widget/blob/main/README.md', /points inside a repository/],
    ['not-a-url', /Only github\.com|not a valid/],
  ])('rejects malformed URL %s with exit 2 and no requests', async (url, re) => {
    const r = await cli([url, '-s', 'professional', '--provider', 'fixture']);
    expect(r.code).toBe(2);
    expect(r.err).toMatch(re);
    expect(r.err).toMatch(/https:\/\/github\.com\/owner\/repo|Try https/);
    expect(r.requests).toEqual([]);
  });

  it('requires url and style when not interactive', async () => {
    expect((await cli(['--provider', 'fixture'])).err).toMatch(/Missing repository URL/);
    const r = await cli([URL_, '--provider', 'fixture']);
    expect(r.code).toBe(2);
    expect(r.err).toMatch(/Missing --style/);
  });

  it('rejects unknown styles via commander', async () => {
    const r = await cli([URL_, '--style', 'fancy']);
    expect(r.code).toBe(2);
    expect(r.err).toMatch(/Allowed choices are professional, trendy, minimalist, comprehensive/);
  });

  it('exits 2 when no provider key is configured, before contacting GitHub', async () => {
    const r = await cli([URL_, '-s', 'professional', '--dry-run']);
    expect(r.code).toBe(2);
    expect(r.err).toMatch(/No generation provider API key found/);
    expect(r.err).toMatch(/REPO2README_API_KEY/);
    expect(r.requests).toEqual([]);
  });

  it('reports a missing or private repository (404)', async () => {
    const r = await cli([URL_, '-s', 'professional', '--dry-run', '--provider', 'fixture'], { fixture: null });
    expect(r.code).toBe(3);
    expect(r.err).toMatch(/not found, or it is private/);
    expect(r.err).toMatch(/public repositories only/);
  });

  it('reports bad credentials (401)', async () => {
    const r = await cli([URL_, '-s', 'professional', '--dry-run', '--provider', 'fixture'], {
      env: { GITHUB_TOKEN: 'expired-token-value' },
      mock: { routes: [{ match: 'api.github.com', respond: () => json({ message: 'Bad credentials' }, 401) }] },
    });
    expect(r.code).toBe(3);
    expect(r.err).toMatch(/401 Unauthorized/);
    expect(r.err).toMatch(/GITHUB_TOKEN is invalid or expired/);
    expect(r.err).not.toContain('expired-token-value');
  });

  it('reports forbidden (403)', async () => {
    const r = await cli([URL_, '-s', 'professional', '--dry-run', '--provider', 'fixture'], {
      mock: { routes: [{ match: 'api.github.com', respond: () => json({ message: 'Repository access blocked' }, 403) }] },
    });
    expect(r.code).toBe(3);
    expect(r.err).toMatch(/403 Forbidden/);
  });

  it('reports rate limiting with the reset time', async () => {
    const reset = Math.floor(Date.now() / 1000) + 1800;
    const r = await cli([URL_, '-s', 'professional', '--dry-run', '--provider', 'fixture'], {
      mock: { routes: [{ match: 'api.github.com', respond: () => json({ message: 'API rate limit exceeded' }, 403, { 'x-ratelimit-remaining': '0', 'x-ratelimit-reset': String(reset) }) }] },
    });
    expect(r.code).toBe(3);
    expect(r.err).toMatch(/rate limit exceeded\. Limit resets at \d{4}-\d\d-\d\d \d\d:\d\d:\d\d/);
    expect(r.err).toMatch(/Set GITHUB_TOKEN/);
  });

  it('reports an empty repository', async () => {
    const r = await cli([URL_, '-s', 'professional', '--dry-run', '--provider', 'fixture'], { mock: { emptyRepo: true } });
    expect(r.code).toBe(3);
    expect(r.err).toMatch(/is empty/);
  });

  it('exits 4 on generation failures', async () => {
    const failing: ReadmeProvider = {
      name: 'failing',
      generateReadme: async () => {
        throw new GenerationError('The generation provider returned HTTP 503.', 'Retry later.');
      },
    };
    const r = await cli([URL_, '-s', 'professional'], { deps: { providerFactory: () => failing } });
    expect(r.code).toBe(4);
    expect(r.err).toMatch(/HTTP 503/);
    expect(r.err).toMatch(/Retry later/);
  });

  it('exits 4 when the real provider rejects the key', async () => {
    const r = await cli([URL_, '-s', 'professional', '--dry-run'], {
      env: { XAI_API_KEY: 'bad-key-123456789' },
      mock: { routes: [{ match: 'api.x.ai', respond: () => json({ error: 'Incorrect API key provided: bad-key-123456789' }, 401) }] },
    });
    expect(r.code).toBe(4);
    expect(r.err).toMatch(/rejected the API key \(401\)/);
    expect(r.err).toMatch(/Check the key in XAI_API_KEY/);
    expect(r.err).not.toContain('bad-key-123456789');
  });

  it('exits 5 and writes nothing when the output fails validation', async () => {
    const sloppy: ReadmeProvider = {
      name: 'sloppy',
      generateReadme: async () => ({ title: 'widget', sections: [{ heading: 'Usage', body: 'TODO: {{usage}}' }], warnings: [] }),
    };
    const r = await cli([URL_, '-s', 'professional'], { deps: { providerFactory: () => sloppy } });
    expect(r.code).toBe(5);
    expect(r.err).toMatch(/failed validation/);
    expect(r.err).toMatch(/Nothing was written/);
    await expect(readFile(path.join(r.cwd, 'README.generated.md'), 'utf8')).rejects.toThrow();
  });

  it('prints help and version with exit 0', async () => {
    const help = await cli(['--help']);
    expect(help.code).toBe(0);
    expect(help.out).toContain('Usage: repo2readme');
    expect(help.out).toContain('minimalist');
    expect(help.out).not.toContain('--provider');
    const version = await cli(['--version']);
    expect(version.code).toBe(0);
    expect(version.out).toMatch(/^\d+\.\d+\.\d+/);
  });
});
