import { describe, expect, it } from 'vitest';
import type { GeneratedReadme } from '../src/generator.js';
import { renderMarkdown, validateReadme, VERIFY_HEADING } from '../src/validate.js';
import { briefFor, fakeSecrets, loadFixture } from './helpers.js';

const gen = (sections: GeneratedReadme['sections'], warnings: string[] = []): GeneratedReadme => ({ title: 'widget', sections, warnings });

describe('renderMarkdown', () => {
  it('renders one H1, H2 sections, and demotes stray headings in bodies', async () => {
    const brief = await briefFor(loadFixture('widget'));
    const md = renderMarkdown(gen([{ heading: '## Usage', body: '# Big\n## Medium\n```sh\n# a comment\n```' }]), brief);
    expect(md).toMatch(/^<!-- Generated by repo2readme/);
    expect(md).toContain('\n# widget\n');
    expect(md).toContain('\n## Usage\n');
    expect(md).toContain('\n### Big\n');
    expect(md).toContain('\n### Medium\n');
    expect(md).toContain('# a comment');
    const outsideFences = md.replace(/```[\s\S]*?```/g, '');
    expect((outsideFences.match(/^# /gm) ?? []).length).toBe(1);
  });
});

describe('validateReadme', () => {
  it('passes a README whose claims all trace to evidence', async () => {
    const brief = await briefFor(loadFixture('widget'));
    const md = renderMarkdown(
      gen([
        { heading: 'Install', body: '```sh\nnpm install --global @acme/widget\n```' },
        { heading: 'Usage', body: 'Run `widget render --config widget.config.json`. Docs: https://widget.acme.dev. See [CONTRIBUTING.md](CONTRIBUTING.md) and [issues](https://github.com/acme/widget/issues).' },
        { heading: 'License', body: 'MIT. See [LICENSE](https://github.com/acme/widget/blob/main/LICENSE).' },
      ]),
      brief,
    );
    const r = validateReadme(md, brief);
    expect(r.errors).toEqual([]);
    expect(r.unverified).toEqual([]);
    expect(r.markdown).not.toContain(VERIFY_HEADING);
    const kinds = r.claims.map((c) => `${c.kind}:${c.value}`);
    expect(kinds).toEqual(
      expect.arrayContaining([
        'command:npm install --global @acme/widget',
        'command:widget render --config widget.config.json',
        'url:https://widget.acme.dev',
        'url:CONTRIBUTING.md',
        'url:https://github.com/acme/widget/issues',
        'license:MIT',
      ]),
    );
  });

  it('flags invented commands, URLs, badges and license claims in a verify section', async () => {
    const brief = await briefFor(loadFixture('widget'));
    const md = renderMarkdown(
      gen(
        [
          { heading: 'Badges', body: '![build](https://img.shields.io/github/actions/workflow/status/acme/widget/ci.yml) ![npm](https://img.shields.io/npm/v/@acme/widget)' },
          { heading: 'Install', body: '```bash\nbrew install widget\nnpm install\n```' },
          { heading: 'More', body: 'Join us on [Discord](https://discord.gg/acme). See [guide](docs/missing.md).' },
          { heading: 'License', body: 'Licensed under the Apache-2.0 license.' },
        ],
        ['The Discord link was not in the brief.'],
      ),
      brief,
    );
    const r = validateReadme(md, brief, ['The Discord link was not in the brief.']);
    expect(r.errors).toEqual([]);
    const flagged = r.unverified.map((c) => `${c.kind}:${c.value}`);
    expect(flagged).toEqual(
      expect.arrayContaining([
        'badge:https://img.shields.io/github/actions/workflow/status/acme/widget/ci.yml',
        'command:brew install widget',
        'url:https://discord.gg/acme',
        'url:docs/missing.md',
        'license:Apache-2.0',
      ]),
    );
    // The npm badge was already in the repository README, so it is evidence-backed.
    expect(flagged).not.toContain('badge:https://img.shields.io/npm/v/@acme/widget');
    expect(flagged).not.toContain('command:npm install');
    expect(r.markdown).toContain(`## ${VERIFY_HEADING}`);
    expect(r.markdown).toContain('**Command** `brew install widget`');
    expect(r.markdown).toContain('**Note:** The Discord link was not in the brief.');
  });

  it('flags any license claim when the repository has none', async () => {
    const brief = await briefFor(loadFixture('pyapp'));
    const md = renderMarkdown(gen([{ heading: 'License', body: 'This project is MIT licensed.' }]), brief);
    const r = validateReadme(md, brief);
    expect(r.unverified).toEqual([expect.objectContaining({ kind: 'license', value: 'MIT', note: 'no license detected in the repository' })]);
  });

  it('flags inferred toolchain commands as needing verification', async () => {
    const brief = await briefFor(loadFixture('pyapp'));
    const md = renderMarkdown(gen([{ heading: 'Install', body: '```sh\npip install .\nmake test\n```' }]), brief);
    const r = validateReadme(md, brief);
    expect(r.unverified.map((c) => c.value)).toEqual(['pip install .']);
    expect(r.unverified[0]?.note).toMatch(/conventional/);
  });

  it.each([
    ['{{project_name}} is great', /template token/],
    ['Install with <% cmd %>', /template token/],
    ['TODO: describe usage', /TODO/],
    ['Lorem ipsum dolor sit amet', /lorem ipsum/],
    ['Clone [insert repo url]', /fill-in placeholder/],
    ['git clone https://github.com/your-username/widget', /placeholder/],
  ])('rejects unresolved placeholders: %s', async (body, re) => {
    const brief = await briefFor(loadFixture('widget'));
    const r = validateReadme(renderMarkdown(gen([{ heading: 'Overview', body }]), brief), brief);
    expect(r.errors.join('\n')).toMatch(re);
  });

  it('allows GitHub Actions ${{ }} expressions inside code blocks', async () => {
    const brief = await briefFor(loadFixture('widget'));
    const r = validateReadme(renderMarkdown(gen([{ heading: 'CI', body: '```yaml\nnode: ${{ matrix.node }}\n```' }]), brief), brief);
    expect(r.errors).toEqual([]);
  });

  it('requires an H1, balanced fences, and non-empty headings', async () => {
    const brief = await briefFor(loadFixture('widget'));
    expect(validateReadme('## Only h2\n\ntext\n', brief).errors.join()).toMatch(/Missing required top-level/);
    expect(validateReadme('# A\n\n```sh\nnpm test\n', brief).errors.join()).toMatch(/Unbalanced code fence/);
    expect(validateReadme('# A\n\n## \n\ntext\n# B\n', brief).errors.join()).toMatch(/Empty heading.*|top-level/);
  });

  it('redacts secrets that appear in generated output', async () => {
    const brief = await briefFor(loadFixture('widget'));
    const tok = fakeSecrets.githubToken();
    const r = validateReadme(renderMarkdown(gen([{ heading: 'Config', body: `export GITHUB_TOKEN=${tok}` }]), brief), brief);
    expect(r.markdown).not.toContain(tok);
    expect(r.markdown).toContain('[REDACTED]');
    expect(r.redactions).toBe(1);
    expect(r.warnings.join()).toMatch(/Redacted 1 potential secret/);
  });

  it('warns on anchors that do not match a heading', async () => {
    const brief = await briefFor(loadFixture('widget'));
    const r = validateReadme(renderMarkdown(gen([{ heading: 'Overview', body: '[x](#usage) [y](#overview)' }]), brief), brief);
    expect(r.warnings.join()).toMatch(/"#usage"/);
    expect(r.warnings.join()).not.toMatch(/"#overview"/);
  });
});
