/**
 * Rendering and validation of generated READMEs: structure, template tokens,
 * secrets, and traceability of fact-sensitive claims (commands, URLs, badges,
 * license statements) back to evidence in the project brief.
 */
import { extractUrls, looksLikeCommand, normalizeCommand, type ProjectBrief } from './brief.js';
import type { GeneratedReadme } from './generator.js';
import { slugify } from './generator.js';
import { scanForSecrets } from './secrets.js';

export type ClaimKind = 'command' | 'url' | 'badge' | 'license';

export interface Claim {
  kind: ClaimKind;
  value: string;
  line: number;
  /** Evidence paths / sources when traced, otherwise null. */
  evidence: string[] | null;
  note?: string;
}

export interface ValidationReport {
  /** Final Markdown, with secrets redacted and a verify section appended when needed. */
  markdown: string;
  errors: string[];
  warnings: string[];
  claims: Claim[];
  unverified: Claim[];
  generatorNotes: string[];
  redactions: number;
}

export const VERIFY_HEADING = 'Verify before publishing';

export function renderMarkdown(gen: GeneratedReadme, brief: ProjectBrief): string {
  const out: string[] = [];
  out.push(
    `<!-- Generated by repo2readme from ${brief.repo.url} (style: ${brief.style.id}). Review every command, link, badge and license statement before publishing. -->`,
  );
  out.push('');
  out.push(`# ${stripHeadingMarks(gen.title)}`);
  for (const s of gen.sections) {
    const heading = stripHeadingMarks(s.heading);
    const body = demoteHeadings(s.body.replace(/\r\n/g, '\n')).trim();
    if (!heading) continue;
    out.push('', `## ${heading}`, '');
    out.push(body || '_No details available._');
  }
  return out.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
}

function stripHeadingMarks(s: string): string {
  return s.replace(/^\s*#+\s*/, '').replace(/\s+/g, ' ').trim();
}

/** Inside a section body, turn # and ## headings into ### so the document keeps one H1. */
function demoteHeadings(body: string): string {
  let inFence = false;
  return body
    .split('\n')
    .map((line) => {
      if (/^\s*(```|~~~)/.test(line)) inFence = !inFence;
      if (!inFence && /^#{1,2}\s/.test(line)) return line.replace(/^#{1,2}/, '###');
      return line;
    })
    .join('\n');
}

interface Line {
  text: string;
  n: number;
  inFence: boolean;
  fenceLang: string;
  isFenceMarker: boolean;
  section: string;
}

function scanLines(markdown: string): { lines: Line[]; unbalancedFence: boolean } {
  const lines: Line[] = [];
  let inFence = false;
  let fenceChar = '';
  let fenceLen = 0;
  let fenceLang = '';
  let section = '';
  markdown.split('\n').forEach((text, i) => {
    const m = text.match(/^\s{0,3}(`{3,}|~{3,})\s*([\w+-]*)/);
    if (m) {
      const marker = m[1] as string;
      if (!inFence) {
        inFence = true;
        fenceChar = marker[0] as string;
        fenceLen = marker.length;
        fenceLang = (m[2] ?? '').toLowerCase();
        lines.push({ text, n: i + 1, inFence: true, fenceLang, isFenceMarker: true, section });
        return;
      }
      if (marker[0] === fenceChar && marker.length >= fenceLen && !(m[2] ?? '').trim()) {
        lines.push({ text, n: i + 1, inFence: true, fenceLang, isFenceMarker: true, section });
        inFence = false;
        return;
      }
    }
    if (!inFence) {
      const h = text.match(/^(#{1,6})\s+(.*)$/);
      if (h) section = (h[2] ?? '').trim();
    }
    lines.push({ text, n: i + 1, inFence, fenceLang: inFence ? fenceLang : '', isFenceMarker: false, section });
  });
  return { lines, unbalancedFence: inFence };
}

const SHELL_LANGS = new Set(['sh', 'bash', 'shell', 'console', 'zsh', 'terminal', 'shell-session', 'powershell', 'ps1', 'cmd', 'fish']);

const TEMPLATE_TOKEN_PATTERNS: Array<[RegExp, string]> = [
  [/(?<!\$)\{\{[^}]*\}\}/, 'template token {{...}}'],
  [/<%[^%]*%>/, 'template token <%...%>'],
  [/\blorem ipsum\b/i, 'lorem ipsum filler'],
  [/\b(TODO|TBD|FIXME|XXX)\b/, 'TODO/TBD marker'],
  [/[[<]\s*(insert|your)[ _-][^\]>]*[\]>]/i, 'fill-in placeholder'],
  [/\bPLACEHOLDER\b/i, 'placeholder text'],
  [/\b(your-username|YOUR_USERNAME|your-org|<owner>|<repo>|<project-name>)\b/, 'unfilled owner/repo placeholder'],
];

const LICENSE_NAME_RE =
  /\b(MIT|ISC|Apache(?:[- ]License)?(?:[- ]?(?:v(?:ersion)?\s?)?2(?:\.0)?)?|(?:A|L)?GPL(?:[- ]?v?[23](?:\.0)?)?(?:[- ]only|[- ]or[- ]later|\+)?|GNU (?:Affero |Lesser )?General Public License|BSD(?:[- ][0-4][- ]Clause)?|MPL(?:[- ]?2\.0)?|Mozilla Public License|Unlicense|CC0(?:-1\.0)?|CC[- ]BY(?:-SA)?(?:[- ]4\.0)?|EPL(?:-2\.0)?|Eclipse Public License|Zlib|WTFPL|BSL-1\.0|Boost Software License|Artistic(?:-2\.0)?)\b/;

function licenseFamily(name: string): string {
  const n = name.toLowerCase().replace(/\s+/g, ' ');
  if (/\bmit\b/.test(n)) return 'mit';
  if (/\bisc\b/.test(n)) return 'isc';
  if (/apache/.test(n)) return 'apache';
  if (/affero|agpl/.test(n)) return 'agpl';
  if (/lesser|lgpl/.test(n)) return 'lgpl';
  if (/gpl|general public/.test(n)) return 'gpl';
  if (/bsd/.test(n) && !/bsl/.test(n)) return 'bsd';
  if (/mpl|mozilla/.test(n)) return 'mpl';
  if (/unlicense/.test(n)) return 'unlicense';
  if (/cc0/.test(n)) return 'cc0';
  if (/cc[- ]by/.test(n)) return 'cc-by';
  if (/epl|eclipse/.test(n)) return 'epl';
  if (/zlib/.test(n)) return 'zlib';
  if (/wtfpl/.test(n)) return 'wtfpl';
  if (/bsl|boost/.test(n)) return 'bsl';
  if (/artistic/.test(n)) return 'artistic';
  return n;
}

function normUrl(u: string): string {
  return u
    .trim()
    .replace(/^http:\/\//i, 'https://')
    .replace(/^https:\/\/www\./i, 'https://')
    .replace(/[#?].*$/, '')
    .replace(/\/+$/, '')
    .toLowerCase();
}

function isBadgeUrl(u: string): boolean {
  return /img\.shields\.io|badgen\.net|badge\.fury\.io|\/badge\.svg|\/badges?\/|codecov\.io\/.+\/graph|coveralls\.io\/repos\/.+\/badge|travis-ci\.(org|com)\/.+\.svg|snyk\.io\/test\/.+\/badge|circleci\.com\/.+\.svg|readthedocs\.org\/projects\/.+\/badge|deepwiki\.com\/badge|packagephobia|bundlephobia\.com\/api/i.test(u);
}

/** Validate a rendered README against the brief and append a verification section. */
export function validateReadme(rendered: string, brief: ProjectBrief, generatorWarnings: string[] = []): ValidationReport {
  const errors: string[] = [];
  const warnings: string[] = [];
  const claims: Claim[] = [];

  // --- Secrets: redact first so nothing downstream (stdout, file) contains them.
  const scan = scanForSecrets(rendered);
  let markdown = scan.redacted;
  if (scan.findings.length) {
    warnings.push(`Redacted ${scan.findings.length} potential secret(s) from the generated README (lines ${[...new Set(scan.findings.map((f) => f.line))].join(', ')}).`);
  }

  const { lines, unbalancedFence } = scanLines(markdown);
  const prose = lines.filter((l) => !l.inFence);

  // --- Structure
  const h1s = prose.filter((l) => /^#\s+\S/.test(l.text));
  if (h1s.length === 0) errors.push('Missing required top-level "# " heading.');
  if (h1s.length > 1) errors.push(`Found ${h1s.length} top-level "# " headings; expected exactly one (lines ${h1s.map((h) => h.n).join(', ')}).`);
  const firstContent = prose.find((l) => l.text.trim() && !/^<!--.*-->$/.test(l.text.trim()));
  if (firstContent && h1s[0] && firstContent.n !== h1s[0].n) warnings.push('The "# " heading is not the first content line.');
  if (unbalancedFence) errors.push('Unbalanced code fence (``` opened but never closed).');
  const headings = prose.map((l) => ({ l, m: l.text.match(/^(#{1,6})\s*(.*)$/) })).filter((h) => h.m);
  let prevLevel = 0;
  for (const { l, m } of headings) {
    const level = (m?.[1] ?? '').length;
    const title = (m?.[2] ?? '').trim();
    if (!title) errors.push(`Empty heading on line ${l.n}.`);
    if (prevLevel && level > prevLevel + 1) warnings.push(`Heading level jumps from H${prevLevel} to H${level} on line ${l.n}.`);
    prevLevel = level;
  }
  if (!markdown.replace(/<!--[\s\S]*?-->/g, '').replace(/^#.*$/gm, '').trim()) errors.push('The README has no content beyond headings.');

  // --- Template tokens
  for (const l of lines) {
    if (l.isFenceMarker) continue;
    for (const [re, label] of TEMPLATE_TOKEN_PATTERNS) {
      if (l.inFence && label.startsWith('TODO')) continue; // code comments may legitimately say TODO
      if (re.test(l.text)) errors.push(`Unresolved ${label} on line ${l.n}: "${l.text.trim().slice(0, 80)}"`);
    }
  }

  // --- Anchor links
  const slugs = new Set(headings.map((h) => slugify((h.m?.[2] ?? '').trim())));
  slugs.add(slugify(VERIFY_HEADING));

  // --- Claims
  const evidenceCommands = new Map(brief.commands.map((c) => [normalizeCommand(c.command), c]));
  const fileTexts = brief.files.map((f) => ({ path: f.path, text: f.content.replace(/\s+/g, ' ') }));
  const traceCommand = (cmd: string, line: number) => {
    const norm = normalizeCommand(cmd);
    if (!norm) return;
    const hint = evidenceCommands.get(norm);
    if (hint && hint.confidence === 'evidence') {
      claims.push({ kind: 'command', value: norm, line, evidence: hint.evidence });
      return;
    }
    const inFile = fileTexts.find((f) => f.text.includes(norm));
    if (inFile) {
      claims.push({ kind: 'command', value: norm, line, evidence: [inFile.path] });
      return;
    }
    if (hint) {
      claims.push({ kind: 'command', value: norm, line, evidence: null, note: `conventional for the toolchain (${hint.evidence.join(', ')}) but not documented in the repository` });
      return;
    }
    claims.push({ kind: 'command', value: norm, line, evidence: null, note: 'not found in repository evidence' });
  };

  let continuation = '';
  for (const l of lines) {
    if (!l.inFence || l.isFenceMarker) {
      continuation = '';
      continue;
    }
    const lang = l.fenceLang;
    if (!SHELL_LANGS.has(lang) && lang !== '') continue;
    let t = l.text.trim();
    if (!t || t.startsWith('#')) continue;
    if (continuation) t = `${continuation} ${t}`;
    if (t.endsWith('\\')) {
      continuation = t.slice(0, -1).trim();
      continue;
    }
    continuation = '';
    const isPrompt = /^(\$|>)\s/.test(t);
    if (lang === '' || lang === 'console') {
      if (!isPrompt && !looksLikeCommand(t)) continue;
    }
    traceCommand(t, l.n);
  }
  for (const l of prose) {
    for (const m of l.text.matchAll(/`([^`\n]+)`/g)) {
      const code = (m[1] as string).trim();
      if (code.includes(' ') && (looksLikeCommand(code) || evidenceCommands.has(normalizeCommand(code)))) traceCommand(code, l.n);
    }
  }

  const repoUrl = normUrl(brief.repo.url);
  const evidenceUrls = new Map(brief.evidenceUrls.map((u) => [normUrl(u), u]));
  const pathSet = new Set(brief.paths);
  const dirSet = new Set(brief.paths.flatMap((p) => p.split('/').slice(0, -1).map((_, i, a) => a.slice(0, i + 1).join('/'))));
  const branch = brief.repo.defaultBranch.toLowerCase();

  const traceUrl = (raw: string, line: number, isImage: boolean) => {
    const url = raw.trim().replace(/^<|>$/g, '').split(/\s+/)[0] ?? '';
    if (!url || url.startsWith('mailto:')) return;
    if (url.startsWith('#')) {
      if (!slugs.has(url.slice(1).toLowerCase())) warnings.push(`Anchor link "${url}" on line ${line} does not match any heading.`);
      return;
    }
    const badge = isImage && isBadgeUrl(url);
    const kind: ClaimKind = badge ? 'badge' : 'url';
    if (!/^https?:\/\//i.test(url)) {
      const p = decodeURIComponent(url.replace(/^\.\//, '').replace(/[#?].*$/, '').replace(/\/$/, ''));
      if (pathSet.has(p) || dirSet.has(p)) claims.push({ kind, value: url, line, evidence: [p] });
      else claims.push({ kind, value: url, line, evidence: null, note: 'relative link to a file not found in the repository' });
      return;
    }
    const n = normUrl(url);
    if (evidenceUrls.has(n)) {
      claims.push({ kind, value: url, line, evidence: [n === repoUrl ? 'github:metadata' : 'repository files / metadata'] });
      return;
    }
    if (badge) {
      claims.push({ kind, value: url, line, evidence: null, note: 'generated badge; confirm the service and value are correct' });
      return;
    }
    if (n === repoUrl || new RegExp(`^${escapeRe(repoUrl)}/(issues|pulls|releases|discussions|wiki|actions|stargazers|network|graphs|security)(/|$)`).test(n)) {
      claims.push({ kind, value: url, line, evidence: ['github:metadata'] });
      return;
    }
    const blob = n.match(new RegExp(`^${escapeRe(repoUrl)}/(?:blob|tree|raw)/([^/]+)/(.+)$`));
    if (blob && blob[1] === branch) {
      const orig = decodeURIComponent(url.replace(/[#?].*$/, '').replace(/\/+$/, '')).split('/').slice(7).join('/');
      if (pathSet.has(orig) || dirSet.has(orig)) {
        claims.push({ kind, value: url, line, evidence: [orig] });
        return;
      }
    }
    claims.push({ kind, value: url, line, evidence: null, note: 'URL not found in repository evidence' });
  };

  for (const l of prose) {
    const seen = new Set<string>();
    for (const m of l.text.matchAll(/(!?)\[(?:[^\]]|\[[^\]]*\])*\]\(([^)\s]+(?:\s+"[^"]*")?)\)/g)) {
      const target = (m[2] as string).replace(/\s+"[^"]*"$/, '');
      seen.add(target);
      traceUrl(target, l.n, m[1] === '!');
    }
    for (const m of l.text.matchAll(/<img[^>]+src=["']([^"']+)["']/gi)) {
      seen.add(m[1] as string);
      traceUrl(m[1] as string, l.n, true);
    }
    for (const m of l.text.matchAll(/^\s*\[[^\]]+\]:\s*(\S+)/g)) {
      seen.add(m[1] as string);
      traceUrl(m[1] as string, l.n, false);
    }
    const withoutCode = l.text.replace(/`[^`]*`/g, '');
    for (const u of extractUrls(withoutCode)) {
      if ([...seen].some((s) => s.includes(u) || u.includes(s))) continue;
      traceUrl(u, l.n, false);
    }
  }

  // License claims: license names in prose within a license-ish context.
  const repoLicense = brief.repo.license;
  const repoFamily = repoLicense ? licenseFamily(`${repoLicense.spdxId ?? ''} ${repoLicense.name}`) : null;
  for (const l of prose) {
    const inLicenseContext = /licen[cs]/i.test(l.text) || /licen[cs]/i.test(l.section);
    if (!inLicenseContext || /^#{1,6}\s/.test(l.text)) continue;
    const text = l.text.replace(/\]\([^)]*\)/g, ']').replace(/https?:\/\/\S+/g, '');
    const m = text.match(LICENSE_NAME_RE);
    if (!m) continue;
    const name = m[1] as string;
    if (repoFamily && licenseFamily(name) === repoFamily) {
      claims.push({ kind: 'license', value: name, line: l.n, evidence: ['github:metadata'] });
    } else {
      claims.push({
        kind: 'license',
        value: name,
        line: l.n,
        evidence: null,
        note: repoLicense ? `GitHub reports ${repoLicense.spdxId ?? repoLicense.name}` : 'no license detected in the repository',
      });
    }
  }

  const unverified = dedupeClaims(claims.filter((c) => c.evidence === null));
  const generatorNotes = [...new Set(generatorWarnings.map((w) => w.trim()).filter(Boolean))];

  if (unverified.length || generatorNotes.length) {
    markdown = appendVerifySection(markdown, unverified, generatorNotes);
  }

  return { markdown, errors, warnings, claims, unverified, generatorNotes, redactions: scan.findings.length };
}

function dedupeClaims(claims: Claim[]): Claim[] {
  const seen = new Set<string>();
  return claims.filter((c) => {
    const k = `${c.kind}\u0000${c.value}`;
    if (seen.has(k)) return false;
    seen.add(k);
    return true;
  });
}

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

const KIND_LABEL: Record<ClaimKind, string> = { command: 'Command', url: 'Link', badge: 'Badge', license: 'License claim' };

function appendVerifySection(markdown: string, unverified: Claim[], notes: string[]): string {
  const items: string[] = [];
  for (const c of unverified) {
    items.push(`- [ ] **${KIND_LABEL[c.kind]}** \`${c.value.replace(/`/g, "'")}\` (line ${c.line}): ${c.note ?? 'not traced to evidence'}`);
  }
  for (const n of notes) items.push(`- [ ] **Note:** ${n.replace(/\n+/g, ' ')}`);
  return (
    markdown.trimEnd() +
    `\n\n## ${VERIFY_HEADING}\n\n` +
    '> [!IMPORTANT]\n> repo2readme could not trace the items below to evidence in the repository. Check each one, then delete this section before publishing.\n\n' +
    items.join('\n') +
    '\n'
  );
}
